apiVersion: v1
kind: Pod
metadata:
  labels:
    app: churro
    pipeline: pipeline1
    service: churro-loader
  name: churro-loader
spec:
  containers:
  - command:
    - /usr/local/bin/churro-loader
    - "-servicecert"
    - "/servicecerts"
    - "-dbcert"
    - "/dbcerts"
    - "-debug"
    - "true"
    env:
    - name: CHURRO_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: registry.gitlab.com/churro-group/churro/churro-loader
    imagePullPolicy: IfNotPresent
    name: churro-loader
    volumeMounts:
    - mountPath: /dbcerts
      name: db-certs
    - mountPath: /servicecerts
      name: service-certs
  restartPolicy: Always
  serviceAccount: churro
  serviceAccountName: churro
  volumes:
  - name: db-certs
    secret:
      defaultMode: 256
      secretName: cockroachdb.client.root
  - name: service-certs
    secret:
      defaultMode: 256
      secretName: churro.client.root
