apiVersion: v1
kind: Pod
metadata:
  labels:
    app: churro-ui
  name: churro-ui
spec:
  containers:
  - image: registry.gitlab.com/churro-group/churro/churro-ui:latest
    imagePullPolicy: IfNotPresent
    name: churro-ui
    volumeMounts:
    - name: db
      mountPath: /db
    env:
    - name: PORT
      value: "8080"
    - name: CHURRO_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
  restartPolicy: Always
  serviceAccount: churro-ui
  serviceAccountName: churro-ui
  volumes:
  - name: db
    persistentVolumeClaim:
      claimName: churro-admindb
